site_name: HTTPCore2
site_description: A minimal HTTP client for Python.
site_url: https://httpcore2.pydantic.dev/
site_dir: site-httpcore2

theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: pydantic/httpx2
repo_url: https://github.com/pydantic/httpx2/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - Requests, Responses, and URLs: 'requests-responses-urls.md'
    - Connection Pools: 'connection-pools.md'
    - Connections: 'connections.md'
    - Proxies: 'proxies.md'
    - HTTP/2: 'http2.md'
    - Async Support: 'async.md'
    - Network Backends: 'network-backends.md'
    - Extensions: 'extensions.md'
    - Logging: 'logging.md'
    - Exceptions: 'exceptions.md'

plugins:
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            line_length: 60
            heading_level: 3
            inherited_members: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
