#!/bin/sh -e

export SOURCE_FILES="src/httpx2 tests/httpx2"

set -x

uv lock --check
uv run ruff format --check --diff $SOURCE_FILES
uv run mypy $SOURCE_FILES
uv run ruff check $SOURCE_FILES
uv run python scripts/unasync.py --check
