name: Pyodide Test Suite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "version-*"]

permissions:
  contents: read

jobs:
  pyodide:
    name: "Pyodide"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install Chrome for Pyodide tests
        uses: pyodide/pyodide-actions/install-browser@012fa537869d343726d01863a34b773fc4d96a14 # v2
        with:
          runner: selenium
          browser: chrome
          browser-version: latest

      - name: Install Node for Pyodide tests
        uses: pyodide/pyodide-actions/install-browser@012fa537869d343726d01863a34b773fc4d96a14 # v2
        with:
          runner: selenium
          browser: node
          browser-version: 22

      - name: Download Pyodide
        uses: pyodide/pyodide-actions/download-pyodide@012fa537869d343726d01863a34b773fc4d96a14 # v2
        with:
          version: 0.29.3
          to: pyodide_dist

      - name: Install dependencies
        run: scripts/install

      - name: Install Pyodide test dependencies
        run: uv pip install -r requirements-emscripten.txt

      - name: Run tests
        run: scripts/test

      - name: Enforce coverage
        run: scripts/coverage
